# Generated by Django 3.2.7 on 2021-09-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EShop', '0003_order_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_address', models.TextField()),
                ('billing_address', models.TextField()),
                ('time_fulfilled', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
